# RATE LIMITING
RATE_LIMIT = 2

# USERS
ROLES = { 
    admin: 0,
    customer: 1,
}

MAX_USERNAME_LENGTH = 20
MAX_NAME_LENGTH = 50
MAX_EMAIL_LENGTH = 50
MAX_ADDRESS_LENGTH = 50
MAX_CITY_LENGTH = 50


# IMAGES
MAX_IMAGE_SIZE = 5  # MB


# PRODUCTS
MAX_PRODUCT_NAME_LENGTH = 50
MAX_PRODUCT_BRAND_LENGTH = 50
MAX_PRODUCT_DESCRIPTION_LENGTH = 2000
MAX_PRODUCT_SPECIFICATION_LENGTH = 2000
MAX_PRODUCT_PRICE_LENGTH = 10


# REVIEWS
MAX_REVIEW_LENGTH = 500